apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: chatbot-oct15-pr-1-gitops-repository
spec:
  url: https://github.com/redhat-appstudio-mjf/chatbot-oct15-pr-1-gitops